<a href="https://colab.research.google.com/github/iammariyas/Summer_Practice/blob/main/%D0%97%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5%202.3%20NumPy%20%D0%92%D0%B5%D0%BA%D1%82%D0%BE%D1%80%20%D0%B8%20%D0%BC%D0%B0%D1%82%D1%80%D0%B8%D1%86%D0%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Задание 2.3 NumPy Вектор и матрица
## Вариант 21

21. Дан вектор $𝑥$ и матрица $𝐴$. Умножить все нечетные строки матрицы $𝐴$ на вектор $𝑥$ в обратном порядке. Результат записать в новую матрицу и найти сумму ее элементов.

* **Примечание 1**. Считать, что размерности вектора и матрицы соответствуют выполняемым операциям.

* **Примечание 2**. Фраза умножение в обратном порядке означает, что умножение происходит по правилу: последний элемент строки на первый элемент вектора, …, первый элемент строки на последний элемент вектора.

In [ ]:
import numpy as np

In [ ]:
A = np.random.randint(0, 100, (4, 3))
A

array([[17, 66, 25],
       [95, 66, 23],
       [52, 42, 57],
       [34, 77, 48]])

In [ ]:
x = np.random.randint(-100, 100, 3)
new_x = x[::-1]
new_x

array([-37,  85, -74])

In [ ]:
new_A = A[1::2, :] * new_x
new_A

array([[-3515,  5610, -1702],
       [-1258,  6545, -3552]])

In [ ]:
np.sum(new_A)

np.int64(2128)