<a href="https://colab.research.google.com/github/iammariyas/Summer_Practice/blob/main/%D0%97%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5%202.1%20NumPy%20%D0%97%D0%BD%D0%B0%D0%BA%D0%BE%D0%BC%D1%81%D1%82%D0%B2%D0%BE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Задание 2.1 NumPy Знакомство

## 23 вариант

In [ ]:
import numpy as np

### 1.       Сгенерировать матрицу размером $12 × 6$, заполненную целыми числами.

In [ ]:
matrix = np.random.randint(0, 1024, (12, 6))
matrix

array([[ 625, 1005,  175,  253,  956,  992],
       [ 319,  302,   39,  278,  648,  504],
       [ 778,  439,  512,  922,  826,  847],
       [ 844,  811,  266,  586,  123,  210],
       [ 576,  936,  583,   69,  361,  898],
       [ 354,  948,  863,   45,   97,  188],
       [ 320,  669,  142,  948,  595,  382],
       [ 303,  938,  335,  680,  219,  544],
       [ 176,  608,   63,   69,  787,  453],
       [ 214,  109,  443,  408,  770,  399],
       [ 954,  281,  995,  953,   46,  465],
       [ 806,   90,  730,  866,  404,  610]])

### 2.       Вывести на экран элемент с индексами $[7, 5]$.

In [ ]:
matrix[7, 5]

np.int64(544)

### 3.       Вывести на экран четвертую строку матрицы.

In [ ]:
matrix[4]

array([576, 936, 583,  69, 361, 898])

### 4.       Вывести на экран предпоследний столбец матрицы в обратном порядке.

In [ ]:
matrix[::-1, -2]

array([404,  46, 770, 787, 219, 595,  97, 361, 123, 826, 648, 956])

### 5.       Изменить форму матрицы с $12 × 6$ на $6 × 12$.

Данное задание можно решить двумя способами:
1. Транспонирование матрицы:

In [ ]:
matrix.T

array([[ 625,  319,  778,  844,  576,  354,  320,  303,  176,  214,  954,
         806],
       [1005,  302,  439,  811,  936,  948,  669,  938,  608,  109,  281,
          90],
       [ 175,   39,  512,  266,  583,  863,  142,  335,   63,  443,  995,
         730],
       [ 253,  278,  922,  586,   69,   45,  948,  680,   69,  408,  953,
         866],
       [ 956,  648,  826,  123,  361,   97,  595,  219,  787,  770,   46,
         404],
       [ 992,  504,  847,  210,  898,  188,  382,  544,  453,  399,  465,
         610]])

2. Метод `reshape`

In [ ]:
matrix.reshape(6, 12)

array([[ 625, 1005,  175,  253,  956,  992,  319,  302,   39,  278,  648,
         504],
       [ 778,  439,  512,  922,  826,  847,  844,  811,  266,  586,  123,
         210],
       [ 576,  936,  583,   69,  361,  898,  354,  948,  863,   45,   97,
         188],
       [ 320,  669,  142,  948,  595,  382,  303,  938,  335,  680,  219,
         544],
       [ 176,  608,   63,   69,  787,  453,  214,  109,  443,  408,  770,
         399],
       [ 954,  281,  995,  953,   46,  465,  806,   90,  730,  866,  404,
         610]])

### 6.       Разделить каждый элемент матрицы на заданное число.

In [ ]:
n = int(input('Задайте число: '))
matrix / n

Задайте число: 2


array([[312.5, 502.5,  87.5, 126.5, 478. , 496. ],
       [159.5, 151. ,  19.5, 139. , 324. , 252. ],
       [389. , 219.5, 256. , 461. , 413. , 423.5],
       [422. , 405.5, 133. , 293. ,  61.5, 105. ],
       [288. , 468. , 291.5,  34.5, 180.5, 449. ],
       [177. , 474. , 431.5,  22.5,  48.5,  94. ],
       [160. , 334.5,  71. , 474. , 297.5, 191. ],
       [151.5, 469. , 167.5, 340. , 109.5, 272. ],
       [ 88. , 304. ,  31.5,  34.5, 393.5, 226.5],
       [107. ,  54.5, 221.5, 204. , 385. , 199.5],
       [477. , 140.5, 497.5, 476.5,  23. , 232.5],
       [403. ,  45. , 365. , 433. , 202. , 305. ]])

### 7.       Найти максимум в каждой строке.

Возвратим максимум по заданной оси `axis=1` — строки, а `axis=0` — столбцы

In [ ]:
np.max(matrix, axis=1)

array([1005,  648,  922,  844,  936,  948,  948,  938,  787,  770,  995,
        866])

### 8.       Найти минимальный элемент на побочной диагонали.

Метод `np.fliplr` отражает матрицу по вертикали, метод `np.diagonal` возвращает главную диагональ матрицы

In [ ]:
np.min(np.diagonal(np.fliplr(matrix)))

np.int64(266)

### 9.       Дан одномерный массив. Определить процент четных и нечетных чисел.

In [ ]:
m = np.random.randint(0, 100, 30)
m

array([24, 28, 51, 92,  1, 59, 65, 34, 85, 89, 28, 42, 34, 85, 48, 96, 52,
       28,  3, 72, 48,  8, 32, 83, 59, 78, 34, 90, 18, 42])

Подсчитаем количество четных и нечетных элементов в массиве:

In [ ]:
even_num = np.sum(m % 2 == 0)
odd_num = len(m) - even_num

Вычислим процент четных и нечетных элементов в массиве:

In [ ]:
f'Процент четных элементов в массиве: {(100 * even_num / len(m)):.2f}'

'Процент четных элементов в массиве: 66.67'

In [ ]:
f'Процент нечетных элементов в массиве: {(100 * odd_num / len(m)):.2f}'

'Процент нечетных элементов в массиве: 33.33'

### 10.   В заданной матрице подсчитать количество двузначных чисел.

Зададим матрицу, с которым мы будем работать в дальнейшем:

In [ ]:
'Задайте размер матрицы'
n, m = map(int, input().split())
mtrx = np.random.randint(0, 1024, (n, m))
mtrx

5 6


array([[869, 500, 354, 733, 512, 981],
       [272, 202, 320, 333, 307,  62],
       [794, 319, 546, 381,  99, 309],
       [170, 295, 903, 486, 346, 894],
       [811, 766, 674, 588, 351, 227]])

In [ ]:
f'Количество двузначных чисел: {np.sum((mtrx >= 10) & (mtrx <= 99))}'

'Количество двузначных чисел: 2'